# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('article_name', models.CharField(max_length=100)),
                ('score_count', models.PositiveIntegerField()),
                ('score_sum', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BiasScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('source_name', models.CharField(max_length=30)),
                ('score_count', models.PositiveIntegerField()),
                ('score_sum', models.PositiveIntegerField()),
                ('score_average', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsfeed.Source'),
        ),
    ]
