# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='score_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='score_sum',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='score_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='source',
            name='score_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='score_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
